import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lib.sig;


public class bibit extends javax.swing.JFrame {
    

    /**
     * Creates new form NewJFrame
     */
    private void tampilbibit(){
        DefaultTableModel bibit = new DefaultTableModel();
        bibit.addColumn("No");
        bibit.addColumn("id");
        bibit.addColumn("Nama bibit");
        bibit.addColumn("Stok");
        try {
            int i = 1;
            String sql = "SELECT * FROM data_bibit" ;
            java.sql.Connection connect = (Connection)koneksi.configDB();
            java.sql.Statement stm = connect.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                bibit.addRow(new Object[]{i++,
                    res.getString(1),res.getString(2),res.getString(3)});
            }
           bibit1.setModel(bibit);
        } 
        catch (SQLException e) {
        }
    }
    private void reset_kolom(){
        txtidbibit.setText(null);
        txtnamabibit.setText(null);
        txtstokbibit.setText(null);
    }
    public bibit() {
        initComponents();
        tampilbibit();
        scalenow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bibit1 = new javax.swing.JTable();
        txtidbibit = new javax.swing.JTextField();
        txtnamabibit = new javax.swing.JTextField();
        txtstokbibit = new javax.swing.JTextField();
        bttnnambah = new javax.swing.JButton();
        bttnhapus = new javax.swing.JButton();
        bttnupdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bttnpanen1 = new javax.swing.JButton();
        bttnpupuk = new javax.swing.JButton();
        bttnbibit = new javax.swing.JButton();
        bttnlogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 500));
        setPreferredSize(new java.awt.Dimension(860, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        jPanel2.setBackground(new java.awt.Color(142, 186, 168));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bibit1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };

        bibit1.getTableHeader().setReorderingAllowed(false);
        bibit1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "value1", "value2", "value3", "value4"
            }
        ));
        bibit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bibit1MouseClicked(evt);
            }
        });
        bibit1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bibit1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(bibit1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 510, 210));

        txtidbibit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidbibitActionPerformed(evt);
            }
        });
        txtidbibit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidbibitKeyPressed(evt);
            }
        });
        jPanel2.add(txtidbibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 420, -1));

        txtnamabibit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabibitActionPerformed(evt);
            }
        });
        txtnamabibit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamabibitKeyPressed(evt);
            }
        });
        jPanel2.add(txtnamabibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 420, -1));

        txtstokbibit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokbibitActionPerformed(evt);
            }
        });
        txtstokbibit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstokbibitKeyPressed(evt);
            }
        });
        jPanel2.add(txtstokbibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 420, -1));

        bttnnambah.setText("tambah");
        bttnnambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnnambahActionPerformed(evt);
            }
        });
        jPanel2.add(bttnnambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        bttnhapus.setText("hapus");
        bttnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnhapusActionPerformed(evt);
            }
        });
        jPanel2.add(bttnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        bttnupdate.setText("update");
        bttnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(bttnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 20));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stok");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 20));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 20));

        bttnpanen1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        bttnpanen1.setForeground(new java.awt.Color(255, 255, 255));
        bttnpanen1.setText("Hasil Panen");
        bttnpanen1.setContentAreaFilled(false);
        bttnpanen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnpanen1ActionPerformed(evt);
            }
        });
        jPanel2.add(bttnpanen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        bttnpupuk.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        bttnpupuk.setForeground(new java.awt.Color(255, 255, 255));
        bttnpupuk.setText("pupuk");
        bttnpupuk.setContentAreaFilled(false);
        bttnpupuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnpupukActionPerformed(evt);
            }
        });
        jPanel2.add(bttnpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 40));

        bttnbibit.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        bttnbibit.setForeground(new java.awt.Color(255, 255, 255));
        bttnbibit.setText("Bibit");
        bttnbibit.setContentAreaFilled(false);
        bttnbibit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnbibitActionPerformed(evt);
            }
        });
        jPanel2.add(bttnbibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 140, 40));

        bttnlogout.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        bttnlogout.setForeground(new java.awt.Color(255, 255, 255));
        bttnlogout.setText("log out");
        bttnlogout.setContentAreaFilled(false);
        bttnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(bttnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 137, 40));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA BIBIT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnlogoutActionPerformed
        try{
            int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar dari program?", "Message", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    JOptionPane.showMessageDialog(null, "Log Out Berhasil");
                    new lojin().show();
                    this.dispose();
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "Okeh :)");
                    break;
                default:
                    break;     
            }
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }                        
    }//GEN-LAST:event_bttnlogoutActionPerformed

    private void bttnpanen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnpanen1ActionPerformed
        new hasilpanen().show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bttnpanen1ActionPerformed

    private void bttnbibitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnbibitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnbibitActionPerformed

    private void bttnpupukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnpupukActionPerformed
        new pupuk().show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bttnpupukActionPerformed

    private void txtstokbibitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokbibitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokbibitActionPerformed

    private void bttnnambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnnambahActionPerformed
        try{
            while (true){
            if(txtnamabibit.getText().matches("[a-zA-Z]+")){
                String sql = "INSERT INTO data_bibit VALUES ('"+txtidbibit.getText()+"','"
                                                           +txtnamabibit.getText()+"','"
                                                           +txtstokbibit.getText()+"')";
                java.sql.Connection connect = (Connection)koneksi.configDB();
                java.sql.PreparedStatement pstm = connect.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            }else{
                JOptionPane.showMessageDialog(null, "Input nama harus huruf!");
                reset_kolom();
                break;
            }
          }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilbibit();
        reset_kolom();        // TODO add your handling code here:
    }//GEN-LAST:event_bttnnambahActionPerformed

    private void bttnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnhapusActionPerformed
            try{
            int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin?", "Message", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    String sql = "DELETE FROM data_bibit WHERE ID='"+txtidbibit.getText()+"'";
                    java.sql.Connection connect = (Connection)koneksi.configDB();
                    java.sql.PreparedStatement pstm = connect.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "Okeh :) ");
                    break;
                default:
                    break;     
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilbibit();
        reset_kolom();// TODO add your handling code here:
    }//GEN-LAST:event_bttnhapusActionPerformed

    private void bibit1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bibit1KeyPressed

    }//GEN-LAST:event_bibit1KeyPressed

    private void bibit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibit1MouseClicked
        int baris = bibit1.rowAtPoint(evt.getPoint());
        String id = bibit1.getValueAt(baris, 1).toString();
        txtidbibit.setText(id);

        String nama = bibit1.getValueAt(baris, 2).toString();
        txtnamabibit.setText(nama);
      
        String stok = bibit1.getValueAt(baris, 3).toString();
        txtstokbibit.setText(stok);

    }//GEN-LAST:event_bibit1MouseClicked

    private void bttnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnupdateActionPerformed
        try{
            int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin?", "Message", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(opsi){
            case JOptionPane.YES_OPTION:
                if(txtnamabibit.getText().matches("[a-zA-Z ]+")){
                    String sql = "UPDATE data_bibit SET ID='"+txtidbibit.getText()+"',namabibit='"
                                                         +txtnamabibit.getText()+"',stok='"
                                                         +txtstokbibit.getText()+"' WHERE ID='"+txtidbibit.getText()+"'";
                    java.sql.Connection connect = (Connection)koneksi.configDB();
                    java.sql.PreparedStatement pstm = connect.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                    break;
                }else{
                JOptionPane.showMessageDialog(null, "Input nama harus huruf!");
                reset_kolom();
                break;
            }
            case JOptionPane.NO_OPTION:
                 JOptionPane.showMessageDialog(null, "Okeh :) ");
                break;
            default:
                 break;     
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilbibit(); 
        reset_kolom();        // TODO add your handling code here:
    }//GEN-LAST:event_bttnupdateActionPerformed

    private void txtidbibitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidbibitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidbibitActionPerformed

    private void txtidbibitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidbibitKeyPressed
        while (true){
            if(txtidbibit.getText().matches("[0-9]*")){
                if(evt.getKeyCode()==10){
                txtnamabibit.requestFocus();
                }
                break; 
            }else{
                JOptionPane.showMessageDialog(null, "Input id harus angka!");
                reset_kolom();
                txtidbibit.requestFocus();
                break;
            }
           
        } 
    }//GEN-LAST:event_txtidbibitKeyPressed

    private void txtnamabibitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamabibitKeyPressed
        if(evt.getKeyCode()==10){
            while (true){
            if(txtnamabibit.getText().matches("[a-zA-Z]+")){
                txtstokbibit.requestFocus();
                break; 
            }else{
                JOptionPane.showMessageDialog(null, "Input nama harus huruf!");
                reset_kolom();
                txtidbibit.requestFocus();
                break;
            } 
        } 
        }      
    }//GEN-LAST:event_txtnamabibitKeyPressed

    private void txtstokbibitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokbibitKeyPressed
        while (true){
            if(txtstokbibit.getText().matches("[0-9]*")){
                if(evt.getKeyCode()==10){
                JOptionPane.showMessageDialog(null, "Pilih Operasi");
                }
                break; 
            }else{
                JOptionPane.showMessageDialog(null, "Input stok harus angka!");
                reset_kolom();
                txtstokbibit.requestFocus(); 
               break;
            }
           
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtstokbibitKeyPressed

    private void txtnamabibitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabibitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabibitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new bibit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bibit1;
    private javax.swing.JButton bttnbibit;
    private javax.swing.JButton bttnhapus;
    private javax.swing.JButton bttnlogout;
    private javax.swing.JButton bttnnambah;
    private javax.swing.JButton bttnpanen1;
    private javax.swing.JButton bttnpupuk;
    private javax.swing.JButton bttnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtidbibit;
    private javax.swing.JTextField txtnamabibit;
    private javax.swing.JTextField txtstokbibit;
    // End of variables declaration//GEN-END:variables
private void scalenow(){
        sig s = new sig();
        jLabel5.setIcon(s.Scale(jLabel5, "gambar/5511807.jpg"));
    }
}
